FROM golang:1.25.3

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
RUN go get github.com/aws/aws-sdk-go-v2/aws
RUN go get github.com/aws/aws-sdk-go-v2/config
RUN go get github.com/aws/aws-sdk-go-v2/credentials
RUN go get github.com/aws/aws-sdk-go-v2/service/s3
RUN go get github.com/aws/aws-sdk-go-v2/service/s3/types
RUN go get cloud.google.com/go/storage
RUN go get github.com/Azure/azure-sdk-for-go/sdk/azcore
RUN go get github.com/Azure/azure-sdk-for-go/sdk/storage/azblob

COPY server ./server
COPY proto ./proto

RUN go build -o /app/server/server ./server

EXPOSE 50051

CMD ["/app/server/server"]
