FROM node:18 as builder

WORKDIR /app/webapp

COPY webapp/package.json webapp/package-lock.json ./
RUN npm install

COPY webapp/public ./public
COPY webapp/src ./src
RUN npm run build

FROM golang:1.25.3

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/webapp/webapp ./webapp

COPY --from=builder /app/webapp/build /app/webapp/build

EXPOSE 8080

CMD ["/app/webapp/webapp"]