version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}"
    volumes:
      - server-data:/app/data
    networks:
      - grpc-network
    depends_on:
      - localstack
      - fake-gcs
      - azurite
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - LOCALSTACK_ENDPOINT=${LOCALSTACK_ENDPOINT}
      - GRPC_SERVER_PORT=${GRPC_SERVER_PORT}
      # GCS emulator
      - STORAGE_EMULATOR_HOST=http://fake-gcs:4443
      - GOOGLE_CLOUD_PROJECT=dev-project
      - GCS_BUCKET_NAME=grpc-sample-bucket
      # Azure Storage emulator
      - AZURE_STORAGE_ENDPOINT=http://azurite:10000
      - AZURE_STORAGE_ACCOUNT_NAME=devstoreaccount1
      - AZURE_STORAGE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      - AZURE_STORAGE_CONTAINER_NAME=grpc-sample-container
      # SQLite database
      - DB_PATH=/app/data/files.db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    networks:
      - grpc-network
    command: ["/app/client/client", "Docker"]
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - grpc-network
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}

  fake-gcs:
    image: fsouza/fake-gcs-server:latest
    command: ["-scheme", "http", "-port", "4443", "-backend", "memory"]
    ports:
      - "4443:4443"
    networks:
      - grpc-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # S3
      - "4510-4559:4510-4559" # Other services
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    networks:
      - grpc-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"  # Blob service
      - "10001:10001"  # Queue service
      - "10002:10002"  # Table service
    command: ["azurite", "--blobHost", "0.0.0.0", "--blobPort", "10000", "--queueHost", "0.0.0.0", "--queuePort", "10001", "--tableHost", "0.0.0.0", "--tablePort", "10002"]
    networks:
      - grpc-network

volumes:
  server-data:

networks:
  grpc-network:
    driver: bridge
